import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import nodeFetch from 'node-fetch';
import { useMemo } from 'react';
import { Tab } from '@headlessui/react';
import { createApi } from 'unsplash-js';
import { GetStaticProps } from 'next/types';
import { Gallery } from '../components';

import bgImage from '../public/photography-bg.jpeg';
import type { Photo } from '../types';
import { getImages } from '../utils/getImages';

const tabs = [
  {
    key: 'all',
    display: 'All',
  },
  {
    key: 'oceans',
    display: 'oceans',
  },
  {
    key: 'forests',
    display: 'Forests',
  },
];

type HomeProps = {
  oceans: Photo[];
  forests: Photo[];
};

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const unsplash = createApi({
    accessKey: process.env.UNSPLASH_ACCESS_KEY as string,
    fetch: nodeFetch as unknown as typeof fetch,
  });

  const [oceans, forests] = await Promise.all([
    getImages(unsplash, 'oceans'),
    getImages(unsplash, 'forests'),
  ]);

  return {
    props: {
      oceans,
      forests,
    },
    revalidate: 600,
  };
};

export default function Home({ oceans, forests }: HomeProps) {
  const allPhotos = useMemo(() => {
    const all = [...oceans, ...forests];
    return all.sort((a, b) => b.likes - a.likes);
  }, [oceans, forests]);
  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src={bgImage}
        className="fixed top-0 left-0 z-0"
        alt="background"
        placeholder="blur"
      />
      <div className="h-full w-full fixed left-0 top-0 z-10 from-stone-900 bg-gradient-to-t" />

      <header className="fixed top-0 w-full z-30 flex justify-between items-center h-[90px] px-10">
        <h1 className="text-xl uppercase font-medium">Photography Portfolio</h1>
        <Link
          href="https://github.com/lifeisbeautifu1"
          target="_blank"
          className="bg-white rounded-3xl px-4 py-2 text-stone-700 hover:bg-opacity-90 transition duration-300 ease-out"
        >
          Get in touch
        </Link>
      </header>
      <main className="pt-[110px] relative z-20">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-12">
              {tabs.map((tab) => (
                <Tab
                  key={tab.key}
                  className="p-2 outline-none border-none uppercase tracking-widest font-[600]"
                >
                  {({ selected }) => (
                    <span
                      className={selected ? 'text-white' : 'text-stone-600'}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className="h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel>
                <Gallery photos={allPhotos} />
              </Tab.Panel>
              <Tab.Panel>
                <Gallery photos={oceans} />
              </Tab.Panel>
              <Tab.Panel>
                <Gallery photos={forests} />
              </Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>
      <footer className="flex relative z-20 justify-center items-center h-[90px] text-lg font-medium uppercase">
        <p>Photography Portfolio</p>
      </footer>
    </div>
  );
}
